site_name: LangChain Couchbase API Reference
site_description: API Reference for the langchain-couchbase package
site_author: LangChain
repo_url: https://github.com/Couchbase-Ecosystem/langchain-couchbase/
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

nav:
  - Home: index.md
